<?php
/**
 * Database Maintenance Module
 * Handles backup, restore, optimization, and archival operations
 */

require_once 'config.php';
require_once 'auth.php';

// Require admin or registrar role for maintenance operations
requireRole(['admin', 'registrar']);

$action = $_POST['action'] ?? $_GET['action'] ?? '';

switch ($action) {
    case 'backup':
        backupDatabase();
        break;
    case 'restore':
        restoreDatabase();
        break;
    case 'getBackupLogs':
        getBackupLogs();
        break;
    case 'optimizeTables':
        optimizeTables();
        break;
    case 'archiveOldEnrollments':
        archiveOldEnrollments();
        break;
    case 'getDatabaseStats':
        getDatabaseStats();
        break;
    default:
        sendResponse(false, 'Invalid action');
}

/**
 * Backup database with custom filename
 */
function backupDatabase() {
    global $conn;
    
    $filename = sanitize($_POST['filename'] ?? '');
    
    // Default filename with current date if not provided
    if (empty($filename)) {
        $filename = 'dbenrollment_backup_' . date('Y-m-d_His') . '.sql';
    }
    
    // Ensure .sql extension
    if (!str_ends_with($filename, '.sql')) {
        $filename .= '.sql';
    }
    
    // Sanitize filename (remove special characters except dash, underscore, dot)
    $filename = preg_replace('/[^a-zA-Z0-9_\-\.]/', '', $filename);
    
    // Create backups directory if not exists
    $backup_dir = __DIR__ . '/backups';
    if (!file_exists($backup_dir)) {
        mkdir($backup_dir, 0755, true);
    }
    
    $filepath = $backup_dir . '/' . $filename;
    
    try {
        // Get all tables
        $tables = [];
        $result = $conn->query("SHOW TABLES");
        while ($row = $result->fetch_array()) {
            $tables[] = $row[0];
        }
        
        // Start SQL dump
        $sql_dump = "-- Database Backup: " . DB_NAME . "\n";
        $sql_dump .= "-- Backup Date: " . date('Y-m-d H:i:s') . "\n";
        $sql_dump .= "-- Generated by Enrollment Management System\n\n";
        $sql_dump .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $sql_dump .= "SET time_zone = \"+00:00\";\n\n";
        $sql_dump .= "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n";
        $sql_dump .= "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n";
        $sql_dump .= "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n";
        $sql_dump .= "/*!40101 SET NAMES utf8mb4 */;\n\n";
        
        // Loop through tables
        foreach ($tables as $table) {
            // Skip views
            $check_view = $conn->query("SHOW FULL TABLES WHERE Tables_in_" . DB_NAME . " = '$table' AND Table_type = 'VIEW'");
            if ($check_view->num_rows > 0) {
                continue;
            }
            
            $sql_dump .= "-- --------------------------------------------------------\n";
            $sql_dump .= "-- Table structure for table `$table`\n";
            $sql_dump .= "-- --------------------------------------------------------\n\n";
            
            // Drop table if exists
            $sql_dump .= "DROP TABLE IF EXISTS `$table`;\n";
            
            // Get table structure
            $create_table = $conn->query("SHOW CREATE TABLE `$table`");
            $row = $create_table->fetch_assoc();
            $sql_dump .= $row['Create Table'] . ";\n\n";
            
            // Get table data
            $data = $conn->query("SELECT * FROM `$table`");
            
            if ($data->num_rows > 0) {
                $sql_dump .= "-- Dumping data for table `$table`\n\n";
                
                while ($row = $data->fetch_assoc()) {
                    $sql_dump .= "INSERT INTO `$table` VALUES (";
                    
                    $values = [];
                    foreach ($row as $value) {
                        if ($value === null) {
                            $values[] = "NULL";
                        } else {
                            $values[] = "'" . $conn->real_escape_string($value) . "'";
                        }
                    }
                    
                    $sql_dump .= implode(", ", $values);
                    $sql_dump .= ");\n";
                }
                
                $sql_dump .= "\n";
            }
        }
        
        $sql_dump .= "/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n";
        $sql_dump .= "/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n";
        $sql_dump .= "/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n";
        
        // Write to file
        file_put_contents($filepath, $sql_dump);
        
        $file_size = filesize($filepath);
        
        // Log backup
        $user_id = $_SESSION['user_id'];
        $log_sql = "INSERT INTO tbl_backup_logs (filename, file_size, backup_date, performed_by, status, notes) 
                    VALUES (?, ?, NOW(), ?, 'success', 'Backup completed successfully')";
        $stmt = $conn->prepare($log_sql);
        $stmt->bind_param("sii", $filename, $file_size, $user_id);
        $stmt->execute();
        
        // Log activity
        logActivity($user_id, 'backup', 'database', null, "Database backup created: $filename");
        
        // Return file for download
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . $file_size);
        readfile($filepath);
        
        // Optionally delete file after download (keep for history)
        // unlink($filepath);
        
        exit;
        
    } catch (Exception $e) {
        // Log failed backup
        $user_id = $_SESSION['user_id'];
        $error_msg = $conn->real_escape_string($e->getMessage());
        $log_sql = "INSERT INTO tbl_backup_logs (filename, backup_date, performed_by, status, notes) 
                    VALUES (?, NOW(), ?, 'failed', ?)";
        $stmt = $conn->prepare($log_sql);
        $stmt->bind_param("sis", $filename, $user_id, $error_msg);
        $stmt->execute();
        
        sendResponse(false, 'Backup failed: ' . $e->getMessage());
    }
}

/**
 * Restore database from uploaded SQL file
 */
function restoreDatabase() {
    global $conn;
    
    if (!isset($_FILES['backup_file'])) {
        sendResponse(false, 'No file uploaded');
        return;
    }
    
    $file = $_FILES['backup_file'];
    
    // Validate file
    if ($file['error'] !== UPLOAD_ERR_OK) {
        sendResponse(false, 'File upload error');
        return;
    }
    
    if ($file['size'] > 50 * 1024 * 1024) { // 50MB limit
        sendResponse(false, 'File too large (max 50MB)');
        return;
    }
    
    $extension = pathinfo($file['name'], PATHINFO_EXTENSION);
    if ($extension !== 'sql') {
        sendResponse(false, 'Only .sql files are allowed');
        return;
    }
    
    try {
        // Read SQL file
        $sql_content = file_get_contents($file['tmp_name']);
        
        // Split into individual queries
        $queries = array_filter(array_map('trim', explode(';', $sql_content)));
        
        // Disable foreign key checks
        $conn->query('SET FOREIGN_KEY_CHECKS = 0');
        
        // Execute queries
        $success_count = 0;
        $error_count = 0;
        
        foreach ($queries as $query) {
            if (empty($query) || substr($query, 0, 2) === '--' || substr($query, 0, 2) === '/*') {
                continue;
            }
            
            if ($conn->query($query)) {
                $success_count++;
            } else {
                $error_count++;
            }
        }
        
        // Re-enable foreign key checks
        $conn->query('SET FOREIGN_KEY_CHECKS = 1');
        
        $user_id = $_SESSION['user_id'];
        logActivity($user_id, 'restore', 'database', null, "Database restored from: {$file['name']}");
        
        sendResponse(true, "Database restored successfully. Executed $success_count queries" . 
                    ($error_count > 0 ? " ($error_count errors)" : ""));
        
    } catch (Exception $e) {
        $conn->query('SET FOREIGN_KEY_CHECKS = 1');
        sendResponse(false, 'Restore failed: ' . $e->getMessage());
    }
}

/**
 * Get backup history
 */
function getBackupLogs() {
    global $conn;
    
    $sql = "SELECT bl.*, u.username, u.full_name 
            FROM tbl_backup_logs bl
            LEFT JOIN tbl_users u ON bl.performed_by = u.user_id
            ORDER BY bl.backup_date DESC
            LIMIT 50";
    
    $result = $conn->query($sql);
    $logs = [];
    
    while ($row = $result->fetch_assoc()) {
        $row['file_size_mb'] = round($row['file_size'] / 1024 / 1024, 2);
        $logs[] = $row;
    }
    
    sendResponse(true, 'Backup logs retrieved', $logs);
}

/**
 * Optimize all database tables
 */
function optimizeTables() {
    global $conn;
    
    try {
        $tables = [];
        $result = $conn->query("SHOW TABLES");
        
        while ($row = $result->fetch_array()) {
            $tables[] = $row[0];
        }
        
        $optimized = [];
        foreach ($tables as $table) {
            $optimize_result = $conn->query("OPTIMIZE TABLE `$table`");
            if ($optimize_result) {
                $optimized[] = $table;
            }
        }
        
        $user_id = $_SESSION['user_id'];
        logActivity($user_id, 'optimize', 'database', null, "Optimized " . count($optimized) . " tables");
        
        sendResponse(true, 'Optimized ' . count($optimized) . ' tables', $optimized);
        
    } catch (Exception $e) {
        sendResponse(false, 'Optimization failed: ' . $e->getMessage());
    }
}

/**
 * Archive old enrollments (completed more than 2 years ago)
 */
function archiveOldEnrollments() {
    global $conn;
    
    try {
        $cutoff_date = date('Y-m-d', strtotime('-2 years'));
        
        // Get enrollments to archive
        $sql = "SELECT e.*, 
                       CONCAT(s.first_name, ' ', s.last_name) as student_name,
                       sec.section_code,
                       c.course_code
                FROM tbl_enrollment e
                INNER JOIN tbl_student s ON e.student_id = s.student_id
                INNER JOIN tbl_section sec ON e.section_id = sec.section_id
                INNER JOIN tbl_course c ON sec.course_id = c.course_id
                WHERE e.date_enrolled < ? 
                    AND e.status IN ('completed', 'dropped', 'failed')
                    AND e.is_deleted = 0";
        
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("s", $cutoff_date);
        $stmt->execute();
        $result = $stmt->get_result();
        
        $archived_count = 0;
        $user_id = $_SESSION['user_id'];
        
        while ($row = $result->fetch_assoc()) {
            $original_data = json_encode($row);
            
            // Insert into archive
            $archive_sql = "INSERT INTO tbl_archived_enrollments 
                           (enrollment_id, student_id, section_id, date_enrolled, status, letter_grade, archived_by, original_data)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            
            $archive_stmt = $conn->prepare($archive_sql);
            $archive_stmt->bind_param("iiissssi", 
                $row['enrollment_id'],
                $row['student_id'],
                $row['section_id'],
                $row['date_enrolled'],
                $row['status'],
                $row['letter_grade'],
                $user_id,
                $original_data
            );
            
            if ($archive_stmt->execute()) {
                // Soft delete original
                $delete_sql = "UPDATE tbl_enrollment SET is_deleted = 1 WHERE enrollment_id = ?";
                $delete_stmt = $conn->prepare($delete_sql);
                $delete_stmt->bind_param("i", $row['enrollment_id']);
                $delete_stmt->execute();
                
                $archived_count++;
            }
        }
        
        logActivity($user_id, 'archive', 'enrollment', null, "Archived $archived_count old enrollments");
        
        sendResponse(true, "Archived $archived_count enrollment records", ['count' => $archived_count]);
        
    } catch (Exception $e) {
        sendResponse(false, 'Archival failed: ' . $e->getMessage());
    }
}

/**
 * Get database statistics
 */
function getDatabaseStats() {
    global $conn;
    
    try {
        $stats = [];
        
        // Table sizes
        $sql = "SELECT 
                    table_name AS 'table',
                    ROUND(((data_length + index_length) / 1024 / 1024), 2) AS 'size_mb'
                FROM information_schema.TABLES 
                WHERE table_schema = ?
                ORDER BY (data_length + index_length) DESC";
        
        $stmt = $conn->prepare($sql);
        $db_name = DB_NAME;
        $stmt->bind_param("s", $db_name);
        $stmt->execute();
        $result = $stmt->get_result();
        
        $stats['table_sizes'] = [];
        while ($row = $result->fetch_assoc()) {
            $stats['table_sizes'][] = $row;
        }
        
        // Record counts
        $tables = ['tbl_student', 'tbl_instructor', 'tbl_course', 'tbl_enrollment', 'tbl_section'];
        $stats['record_counts'] = [];
        
        foreach ($tables as $table) {
            $count_result = $conn->query("SELECT COUNT(*) as count FROM $table WHERE is_deleted = 0");
            $count_row = $count_result->fetch_assoc();
            $stats['record_counts'][$table] = $count_row['count'];
        }
        
        // Last backup
        $last_backup = $conn->query("SELECT * FROM tbl_backup_logs WHERE status = 'success' ORDER BY backup_date DESC LIMIT 1");
        $stats['last_backup'] = $last_backup->fetch_assoc();
        
        sendResponse(true, 'Database statistics retrieved', $stats);
        
    } catch (Exception $e) {
        sendResponse(false, 'Failed to get statistics: ' . $e->getMessage());
    }
}
